trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# 2. Show Terraform version
- script: terraform -version
  displayName: 'Check Terraform Version'
  

# 3. Terraform Init
- script: |
    terraform init \
      -backend-config="resource_group_name=my-tfstate-rg" \
      -backend-config="storage_account_name=mytfstate" \
      -backend-config="container_name=tfstate" \
      -backend-config="key=terraform.tfstate"
  displayName: 'Terraform Init'
  

# 4. Terraform Plan
- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'
  

# 5. Manual Approval (before Apply)
#- task: ManualValidation@0
#  inputs:
 #   instructions: 'Please review the Terraform plan before applying changes.'
  #  onTimeout: 'reject'
  #displayName: 'Approval before Apply'

# 6. Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
  
