# Starter pipeline - Terraform with self-hosted agent (Windows/Linux compatible)
resources:
  repositories:
    - repository: self
      type: github
      name: vivekprasat/devopstraining1
      ref: refs/heads/main

jobs:
- deployment: Self_hosted_agent
  pool:
    name: Default   # self-hosted agent pool
    demands:
      - agent.name -equals DESKTOP-FESMJVB
  continueOnError: false
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
          # Install Terraform
          # - task: TerraformInstaller@1
          #   inputs:
          #     terraformVersion: 'latest'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'terraform -version'
              errorActionPreference: 'silentlyContinue'
              verbosePreference: 'silentlyContinue'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azuredevops'
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: 'az'
              useGlobalConfig: true
          # # Check Terraform Version
          # - bash: |
          #     terraform -version
          #   displayName: 'Check Terraform Version'

          # Terraform Init
          # - bash: |
          #     terraform init \
          #       -backend-config="resource_group_name=my-tfstate-rg" \
          #       -backend-config="storage_account_name=mytfstateaccount" \
          #       -backend-config="container_name=tfstate" \
          #       -backend-config="key=terraform.tfstate"
          #   displayName: 'Terraform Init'

          # # Terraform Plan
          # - bash: |
          #     terraform plan -out=tfplan
          #   displayName: 'Terraform Plan'

          # (Optional) Terraform Apply
          # Uncomment this if you want to auto-deploy
          # - bash: |
          #     terraform apply -auto-approve tfplan
          #   displayName: 'Terraform Apply'
