trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals vivek

stages:
- stage: InstallAzureCLI
  displayName: "Install Azure CLI"
  jobs:
  - job: InstallCLI
    displayName: "Install Azure CLI on Ubuntu"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az version
      displayName: "Install Azure CLI and verify"

- stage: Terraform
  displayName: "Terraform Plan and Apply"
  jobs:
  - job: TerraformJob
    displayName: "Run Terraform"
    steps:
    - script: sudo apt-get update && sudo apt-get install -y unzip
      displayName: "Install unzip"

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: terraform -version
      displayName: "Check Terraform Version"

    - script: terraform init
      displayName: "Terraform Initialising"

    - script: terraform plan
      displayName: "Terraform Planning"

- stage: Approval
  displayName: "Manual Approval"
  dependsOn: Terraform
  jobs:
  - job: WaitForApproval
    displayName: "Wait for Manual Approval"
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'vsrajan2k@gmail.com'
        instructions: 'Please validate the Terraform plan and approve to proceed.'
        onTimeout: 'reject'
        timeoutInMinutes: 1440

- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Approval
  jobs:
  - job: ApplyTerraform
    displayName: "Apply Terraform Changes"
    steps:
    - script: terraform apply --auto-approve
      displayName: "Terraform Apply"
