
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: self
      type: github
      name: vivekprasat/devopstraining1
      ref: refs/heads/main

jobs:
- deployment: Self_hosted_agent
  pool:
    vmImage: ubuntu-latest
  continueOnError: false
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
