trigger:
- main

resources:
  repositories:
    - repository: self
      type: github
      name: vivekprasat/devopstraining1
      ref: refs/heads/main

pool:
  name: Default
  demands:
    - agent.name -equals vivek

stages:
- stage: InitAndPlan
  displayName: "Terraform Init"
  jobs:
  - job: TerraformJob
    displayName: "Run Terraform Init"
    steps:
    - script: sudo apt-get update && sudo apt-get install -y unzip
      displayName: "Install unzip"

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - script: terraform -version
      displayName: "Check Terraform Version"

    - script: terraform init
      displayName: "Terraform Initialising"

    - script: terraform plan
      displayName: "Terraform Planning"

    # ✅ Manual approval before apply
    
    - script: terraform apply --auto-approve
      displayName: "Terraform Apply"

- stage: PlanAndApply
  displayName: "Terraform Plan and Apply"
  dependsOn: InitAndPlan
  jobs:
  - job: TerraformJob
    displayName: "Run Terraform Plan & Apply"
    steps:
    - script: terraform init
      displayName: "Terraform Initialising"

    - script: terraform plan
      displayName: "Run Terraform Plan"


    - script: terraform apply --auto-approve
      displayName: "Run Terraform Apply"
