# Starter pipeline - Terraform with self-hosted agent
resources:
  repositories:
    - repository: self
      type: github
      name: vivekprasat/devopstraining1
      ref: refs/heads/main

jobs:
- deployment: Self_hosted_agent
  pool:
    name: Default   # self-hosted agent pool
    demands:
      - agent.name -equals DESKTOP-FESMJVB
  continueOnError: false
  environment: dev
  strategy:
    runOnce:
      deploy:
        steps:
          # Install Terraform
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          # Terraform Init
          - script: |
              terraform init \
                -backend-config="resource_group_name=my-tfstate-rg" \
                -backend-config="storage_account_name=mytfstateaccount" \
                -backend-config="container_name=tfstate" \
                -backend-config="key=terraform.tfstate"
            displayName: 'Terraform Init'

          # Terraform Plan
          - script: |
              terraform plan -out=tfplan
            displayName: 'Terraform Plan'

          # (Optional) Terraform Apply
          # Uncomment this if you want to apply automatically
          # - script: |
          #     terraform apply -auto-approve tfplan
          #   displayName: 'Terraform Apply'
